In [1]:
from funcoes import *
from avaliacao import *
from resultado import *
from constantes import *

/home/yulli/anaconda2/envs/envp3/lib/python3.7/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [2]:
import pandas as pd
from resultado import *
from avaliacao import *
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [3]:
datasetDF = readDataset('id')
datasetDF.replace('M', 1, inplace=True)
datasetDF.replace('B', 0, inplace=True)

In [4]:
datasetDF.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                          
842302            1        17.99         10.38          122.80     1001.0   
842517            1        20.57         17.77          132.90     1326.0   
84300903          1        19.69         21.25          130.00     1203.0   
84348301          1        11.42         20.38           77.58      386.1   
84358402          1        20.29         14.34          135.10     1297.0   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
842302            0.11840           0.27760          0.3001   
842517            0.08474           0.07864          0.0869   
84300903          0.10960           0.15990          0.1974   
84348301          0.14250           0.28390          0.2414   
84358402          0.10030           0.13280          0.1980   

          concave points_mean  symmetry_mean  ...  radius_worst  \
id                                            ...                 
842302                0.14710         0.2419  ...         25.38   
842517                0.07017         0.1812  ...         24.99   
84300903              0.12790         0.2069  ...         23.57   
84348301              0.10520         0.2597  ...         14.91   
84358402              0.10430         0.1809  ...         22.54   

          texture_worst  perimeter_worst  area_worst  smoothness_worst  \
id                                                                       
842302            17.33           184.60      2019.0            0.1622   
842517            23.41           158.80      1956.0            0.1238   
84300903          25.53           152.50      1709.0            0.1444   
84348301          26.50            98.87       567.7            0.2098   
84358402          16.67           152.20      1575.0            0.1374   

          compactness_worst  concavity_worst  concave points_worst  \
id                                                                   
842302               0.6656           0.7119                0.2654   
842517               0.1866           0.2416                0.1860   
84300903             0.4245           0.4504                0.2430   
84348301             0.8663           0.6869                0.2575   
84358402             0.2050           0.4000                0.1625   

          symmetry_worst  fractal_dimension_worst  
id                                                 
842302            0.4601                  0.11890  
842517            0.2750                  0.08902  
84300903          0.3613                  0.08758  
84348301          0.6638                  0.17300  
84358402          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
ml_methods_params = [DecisionTreeClassifier(min_samples_split=0.0002,random_state=1),
                     DecisionTreeClassifier(min_samples_split=0.25,random_state=1),
                     DecisionTreeClassifier(min_samples_split=0.5,random_state=1)]

expDecisionTree = Experimento(Fold.gerar_k_folds(datasetDF,5,CLASSE), ml_methods_params)
expDecisionTree.saveFolds('tree')

In [6]:
ml_methods_params = []
for i in range(-1,7,2):
    ml_methods_params += [SVC(kernel='linear', C=2**i)]
expSVMlinear = Experimento(Fold.gerar_k_folds(datasetDF,5,CLASSE), ml_methods_params)

In [7]:
ml_methods_params = []
for i in range(-1,7,2):
    for j in range(-1,5,2):
        ml_methods_params += [SVC(kernel='rbf', C=2**i, gamma=2**j)]
expSVMRBF = Experimento(Fold.gerar_k_folds(datasetDF,5,CLASSE), ml_methods_params)

In [8]:
ml_methods_params = []
for i in range(2,10,2):
    ml_methods_params += [KNeighborsClassifier(n_neighbors=2**i)]
expKNN = Experimento(Fold.gerar_k_folds(datasetDF,5,CLASSE), ml_methods_params)

In [9]:
def resultados(nome_metodo, experimento):
    np.set_printoptions(precision=2)
    print(" === " + str(nome_metodo) + " === ")
    print("Numero de folds: " + str(len(experimento.folds)))
    print("Macro f1: " + str(experimento.macro_f1_avg))
    
    for count in range(len(experimento.resultados)):
        print(str(count) + "\tprecisao: " 
              + str(experimento.resultados[count].precisao) 
              + "\trevocacao: " + str(experimento.resultados[count].revocacao))
        print(experimento.resultados[count].mat_confusao)

# <font color='red'>Importante!! - necessário corrigir os resultados </font>


<font color='red'> o método validacao_melhor_metodo() deve ser chamado dentro do método resultados() para que seja exibido os melhores resultados de cada método. Da forma como está, todos os resultados estão sendo exibidos</font>

In [10]:
resultados("Arvore de decisão", expDecisionTree)

 === Arvore de decisão === 
Numero de folds: 5
Macro f1: 0.9117514792316701
0	precisao: [0.93 0.97]	revocacao: [0.99 0.88]
[[70.  1.]
 [ 5. 37.]]
1	precisao: [0.87 0.89]	revocacao: [0.94 0.76]
[[67.  4.]
 [10. 32.]]
2	precisao: [0.93 0.86]	revocacao: [0.92 0.88]
[[65.  6.]
 [ 5. 37.]]
3	precisao: [0.95 0.87]	revocacao: [0.93 0.89]
[[71.  5.]
 [ 4. 33.]]
4	precisao: [0.96 0.83]	revocacao: [0.91 0.92]
[[69.  7.]
 [ 3. 34.]]
5	precisao: [0.98 0.69]	revocacao: [0.79 0.97]
[[60. 16.]
 [ 1. 36.]]
6	precisao: [0.91 0.84]	revocacao: [0.88 0.87]
[[58.  8.]
 [ 6. 41.]]
7	precisao: [0.91 0.85]	revocacao: [0.89 0.87]
[[59.  7.]
 [ 6. 41.]]
8	precisao: [0.91 0.84]	revocacao: [0.88 0.87]
[[58.  8.]
 [ 6. 41.]]
9	precisao: [0.96 0.95]	revocacao: [0.97 0.93]
[[71.  2.]
 [ 3. 37.]]
10	precisao: [0.97 0.93]	revocacao: [0.96 0.95]
[[70.  3.]
 [ 2. 38.]]
11	precisao: [1.   0.91]	revocacao: [0.95 1.  ]
[[69.  4.]
 [ 0. 40.]]
12	precisao: [0.93 0.98]	revocacao: [0.99 0.89]
[[70.  1.]
 [ 5. 41.]]
13	precisao

In [11]:
resultados("SVM linear", expSVMlinear)

 === SVM linear === 
Numero de folds: 5
Macro f1: 0.9479887828869196
0	precisao: [0.93 1.  ]	revocacao: [1.   0.88]
[[71.  0.]
 [ 5. 37.]]
1	precisao: [0.93 1.  ]	revocacao: [1.   0.88]
[[71.  0.]
 [ 5. 37.]]
2	precisao: [0.95 1.  ]	revocacao: [1.  0.9]
[[71.  0.]
 [ 4. 38.]]
3	precisao: [0.95 0.97]	revocacao: [0.99 0.9 ]
[[70.  1.]
 [ 4. 38.]]
4	precisao: [0.95 0.92]	revocacao: [0.96 0.89]
[[73.  3.]
 [ 4. 33.]]
5	precisao: [0.96 0.92]	revocacao: [0.96 0.92]
[[73.  3.]
 [ 3. 34.]]
6	precisao: [0.97 0.92]	revocacao: [0.96 0.95]
[[73.  3.]
 [ 2. 35.]]
7	precisao: [0.99 0.86]	revocacao: [0.92 0.97]
[[70.  6.]
 [ 1. 36.]]
8	precisao: [0.93 0.93]	revocacao: [0.95 0.89]
[[63.  3.]
 [ 5. 42.]]
9	precisao: [0.93 0.91]	revocacao: [0.94 0.89]
[[62.  4.]
 [ 5. 42.]]
10	precisao: [0.94 0.93]	revocacao: [0.95 0.91]
[[63.  3.]
 [ 4. 43.]]
11	precisao: [0.94 0.93]	revocacao: [0.95 0.91]
[[63.  3.]
 [ 4. 43.]]
12	precisao: [0.95 0.97]	revocacao: [0.99 0.9 ]
[[72.  1.]
 [ 4. 36.]]
13	precisao: [0.95 0

In [12]:
resultados("SVM RBF", expSVMRBF)

 === SVM RBF === 
Numero de folds: 5
Macro f1: 0.38536674877606614
0	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
1	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
2	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
3	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
4	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
5	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
6	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
7	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
8	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
9	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
10	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
11	precisao: [0.63 0.  ]	revocacao: [1. 0.]
[[71.  0.]
 [42.  0.]]
12	precisao: [0.67 0.  ]	revocacao: [1. 0.]
[[76.  0.]
 [37.  0.]]
13	precisao: [0.67 0.  ]	revocacao: [1. 0.]
[[76.  0.]
 [37.  0.]]
14	pr

/home/yulli/Desktop/Github/CancerDetection/resultado.py:70: UndefinedMetricWarning: Não há elementos previstos para a classe 1 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)


In [13]:
resultados("KNN", expKNN)

 === KNN === 
Numero de folds: 5
Macro f1: 0.8904752864974267
0	precisao: [0.92 0.97]	revocacao: [0.99 0.86]
[[70.  1.]
 [ 6. 36.]]
1	precisao: [0.89 0.97]	revocacao: [0.99 0.79]
[[70.  1.]
 [ 9. 33.]]
2	precisao: [0.86 1.  ]	revocacao: [1.   0.71]
[[71.  0.]
 [12. 30.]]
3	precisao: [0.77 1.  ]	revocacao: [1.  0.5]
[[71.  0.]
 [21. 21.]]
4	precisao: [0.94 0.89]	revocacao: [0.95 0.86]
[[72.  4.]
 [ 5. 32.]]
5	precisao: [0.96 0.89]	revocacao: [0.95 0.92]
[[72.  4.]
 [ 3. 34.]]
6	precisao: [0.95 0.92]	revocacao: [0.96 0.89]
[[73.  3.]
 [ 4. 33.]]
7	precisao: [0.85 1.  ]	revocacao: [1.   0.65]
[[76.  0.]
 [13. 24.]]
8	precisao: [0.9  0.93]	revocacao: [0.95 0.85]
[[63.  3.]
 [ 7. 40.]]
9	precisao: [0.9  0.93]	revocacao: [0.95 0.85]
[[63.  3.]
 [ 7. 40.]]
10	precisao: [0.86 0.95]	revocacao: [0.97 0.79]
[[64.  2.]
 [10. 37.]]
11	precisao: [0.81 1.  ]	revocacao: [1.   0.68]
[[66.  0.]
 [15. 32.]]
12	precisao: [0.93 0.95]	revocacao: [0.97 0.88]
[[71.  2.]
 [ 5. 35.]]
13	precisao: [0.92 0.97]	re